// 공명(GONMYUNG) AI 엔진 — K-Content 특화 마스터링 프리셋
// 핵심(core) 3개 → 일반(standard) 17개 순서로 배치

import type { GonmyungPreset } from "./types";

export const GONMYUNG_PRESETS: GonmyungPreset[] = [
  // ── K-Content 핵심 장르 (core) ──
  {
    id: 1,
    genre: "kpop",
    name: "K-Pop (댄스/아이돌)",
    mood: "에너지",
    tier: "core",
    isKContent: true,
    base_frequency: 440,
    bpm: [100, 130],
    eq: { low: 2, mid: 4, high: 5 },
    reverb: 0.3,
    compression: 0.7,
  },
  {
    id: 21,
    name: "K-드라마 OST",
    genre: "kdrama",
    mood: "서정",
    tier: "core",
    isKContent: true,
    base_frequency: 261,
    bpm: [60, 90],
    eq: { low: 3, mid: 6, high: 4 },
    reverb: 0.7,
    compression: 0.3,
  },
  {
    id: 22,
    name: "트로트 퓨전",
    genre: "trot",
    mood: "정서",
    tier: "core",
    isKContent: true,
    base_frequency: 220,
    bpm: [90, 130],
    eq: { low: 4, mid: 5, high: 3 },
    reverb: 0.4,
    compression: 0.5,
  },
  // ── 기타 장르 (standard) ──
  {
    id: 2,
    genre: "hiphop",
    name: "힙합 스트리트 펀치",
    mood: "강렬",
    tier: "standard",
    base_frequency: 80,
    bpm: [80, 100],
    eq: { low: 6, mid: 3, high: 2 },
    reverb: 0.2,
    compression: 0.8,
  },
  {
    id: 3,
    genre: "rnb",
    name: "R&B 소울 글로우",
    mood: "감성",
    tier: "standard",
    base_frequency: 220,
    bpm: [60, 90],
    eq: { low: 4, mid: 5, high: 3 },
    reverb: 0.5,
    compression: 0.5,
  },
  {
    id: 4,
    genre: "edm",
    name: "EDM 클럽 폭발",
    mood: "폭발",
    tier: "standard",
    base_frequency: 130,
    bpm: [125, 150],
    eq: { low: 5, mid: 3, high: 5 },
    reverb: 0.4,
    compression: 0.9,
  },
  {
    id: 5,
    genre: "ambient",
    name: "앰비언트 심연",
    mood: "명상",
    tier: "standard",
    base_frequency: 174,
    bpm: [60, 80],
    eq: { low: 3, mid: 4, high: 4 },
    reverb: 0.9,
    compression: 0.2,
  },
  {
    id: 6,
    genre: "rock",
    name: "록 라이브 파워",
    mood: "파워",
    tier: "standard",
    base_frequency: 110,
    bpm: [110, 140],
    eq: { low: 4, mid: 5, high: 4 },
    reverb: 0.3,
    compression: 0.7,
  },
  {
    id: 7,
    genre: "jazz",
    name: "재즈 클럽 나이트",
    mood: "세련",
    tier: "standard",
    base_frequency: 261,
    bpm: [90, 130],
    eq: { low: 3, mid: 5, high: 4 },
    reverb: 0.6,
    compression: 0.3,
  },
  {
    id: 8,
    genre: "classical",
    name: "클래식 콘서트홀",
    mood: "우아",
    tier: "standard",
    base_frequency: 523,
    bpm: [60, 120],
    eq: { low: 3, mid: 4, high: 5 },
    reverb: 0.8,
    compression: 0.2,
  },
  {
    id: 9,
    genre: "trap",
    name: "트랩 다크 808",
    mood: "다크",
    tier: "standard",
    base_frequency: 60,
    bpm: [130, 170],
    eq: { low: 7, mid: 2, high: 3 },
    reverb: 0.2,
    compression: 0.9,
  },
  {
    id: 10,
    genre: "lofi",
    name: "Lo-Fi 새벽 카페",
    mood: "몽환",
    tier: "standard",
    base_frequency: 196,
    bpm: [70, 90],
    eq: { low: 4, mid: 4, high: 2 },
    reverb: 0.6,
    compression: 0.4,
  },
  {
    id: 11,
    genre: "house",
    name: "하우스 딥 선셋",
    mood: "그루브",
    tier: "standard",
    base_frequency: 130,
    bpm: [120, 130],
    eq: { low: 5, mid: 4, high: 4 },
    reverb: 0.4,
    compression: 0.6,
  },
  {
    id: 12,
    genre: "drill",
    name: "드릴 UK 메탈릭",
    mood: "메탈릭",
    tier: "standard",
    base_frequency: 70,
    bpm: [140, 150],
    eq: { low: 6, mid: 3, high: 4 },
    reverb: 0.2,
    compression: 0.8,
  },
  {
    id: 13,
    genre: "indie",
    name: "인디 루프 텍스처",
    mood: "감성",
    tier: "standard",
    base_frequency: 329,
    bpm: [100, 130],
    eq: { low: 3, mid: 5, high: 4 },
    reverb: 0.5,
    compression: 0.4,
  },
  {
    id: 14,
    genre: "folk",
    name: "포크 어쿠스틱 온기",
    mood: "따뜻",
    tier: "standard",
    base_frequency: 293,
    bpm: [80, 110],
    eq: { low: 3, mid: 5, high: 3 },
    reverb: 0.5,
    compression: 0.3,
  },
  {
    id: 15,
    genre: "metal",
    name: "메탈 하이게인 벽",
    mood: "공격",
    tier: "standard",
    base_frequency: 82,
    bpm: [120, 180],
    eq: { low: 5, mid: 6, high: 5 },
    reverb: 0.2,
    compression: 0.9,
  },
  {
    id: 16,
    genre: "funk",
    name: "펑크 그루브 슬랩",
    mood: "슬랩",
    tier: "standard",
    base_frequency: 165,
    bpm: [100, 120],
    eq: { low: 5, mid: 4, high: 3 },
    reverb: 0.3,
    compression: 0.6,
  },
  {
    id: 17,
    genre: "soul",
    name: "소울 빈티지 따뜻함",
    mood: "빈티지",
    tier: "standard",
    base_frequency: 247,
    bpm: [70, 100],
    eq: { low: 4, mid: 5, high: 3 },
    reverb: 0.5,
    compression: 0.4,
  },
  {
    id: 18,
    genre: "cinematic",
    name: "시네마틱 오케스트라",
    mood: "서사",
    tier: "standard",
    base_frequency: 392,
    bpm: [60, 100],
    eq: { low: 4, mid: 4, high: 5 },
    reverb: 0.8,
    compression: 0.3,
  },
  {
    id: 19,
    genre: "reggae",
    name: "레게 선셋 아일랜드",
    mood: "릴랙스",
    tier: "standard",
    base_frequency: 146,
    bpm: [70, 90],
    eq: { low: 5, mid: 3, high: 2 },
    reverb: 0.4,
    compression: 0.5,
  },
  {
    id: 20,
    genre: "experimental",
    name: "실험적 공명 해체",
    mood: "해체",
    tier: "standard",
    base_frequency: 528,
    bpm: [50, 200],
    eq: { low: 3, mid: 3, high: 6 },
    reverb: 0.7,
    compression: 0.5,
  },
];
